Mayhem initial integration
mayhemheroes/pytils pull request #1
Opened 2022-06-29 06:08 UTC by code-terror

2022-07-30 05:19 UTC, xansec requested changes
Please make the requested changes.

2022-07-30 05:19 UTC, xansec commented on Mayhemfile
> +project: pytils
Cmd needs to be updated to just the name of the python file to avoid fuzzing python.

2022-07-30 07:15 UTC, code-terror commented on Mayhemfile
> +project: pytils
@xansec tried omitting python...The analysis fails..

2022-08-02 05:52 UTC, xansec commented on Mayhemfile
> +project: pytils
You will need to handle your exceptions:

```
 === Uncaught Python exception: ===
ValueError: Value must be positive or zero, not -84
Traceback (most recent call last):
  File "fuzz-numeral.py", line 9, in TestOneInput
    numeral.in_words(fdp.ConsumeInt(len(data)))
  File "/pytils/numeral.py", line 306, in in_words
    check_positive(amount)
  File "/pytils/utils.py", line 40, in check_positive
    raise ValueError("Value must be positive or zero, not %s" % str(value))
```

2022-08-02 05:54 UTC, merged

2022-08-02 05:58 UTC, xansec commented on Mayhemfile
> +project: pytils
And add exec permissions